site_name: Plim
nav:
  - Home: index.md
  - Installation: installation.md
  - Examples: examples.md
theme:
  name: material
  features:
    - content.code.copy

hooks:
  - docs/hooks.py

markdown_extensions:
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            merge_init_into_class: true
