[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name="plim"
version="0.0.1"
dependencies = [
        'numpy<2',
        'scipy',
        'scikit-image',
        'matplotlib',
        'tifffile',
        'napari<0.7',
        'PyQt5',
        'qtpy',
        'magicgui',
        'pyqtgraph',
        'pyserial',
        'lmfit',
        'pytest',
        'pyshortcuts',
        ]
requires-python='>=3.9'
authors = [
        {name = "Ondrej Stranik", email = "ondra.stranik@gmail.com"},
]

description="package for plasmon imaging"
readme = "README.md"
license = "MIT"
keywords = ["instrumentation"]
classifiers = [
  "Development Status :: 3- Alpha",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
]

[project.scripts]
runRealIFC = "plim.main.runRealIFC:main"
runVirtualIFC = "plim.main.runVirtualIFC:main"
runRealMSC = "plim.main.runRealMSC:main"
runSImageAnalyser = "plim.main.runSImageAnalyser:main"
runSignalAnalyser = "plim.main.runSignalAnalyser:main"
plim-create-shortcut = "plim._install.createShortcut:main"

[project.optional-dependencies]
docs = [
        'mkdocs',
        'mkdocs-material',
        'mkdocstrings[python]',
        ]
all = [
        'viscope @ git+https://github.com/ondrejstranik/viscope.git',
        'spectralCamera @ git+https://github.com/ondrejstranik/spectralCamera.git',
        ]

[project.urls]
Repository = "https://github.com/ondrejstranik/plim"

[tool.setuptools.packages.find]
include = ["plim*"]
